object Browse {
val browse =
.exec(http("Browse_3")
			.get("/computers"))
		.pause(8)
		.exec(http("Browse_4")
			.get("/computers?f=macbook"))
		.pause(1)
		.exec(http("Browse_5")
			.get("/computers/519"))
		.pause(2)
		.exec(http("Browse_6")
			.get("/computers"))
		.pause(4)
		.exec(http("Browse_7")
			.get("/computers?f=Iphone"))
		.pause(2)
		.exec(http("Browse_8")
			.get("/computers/523"))
		.pause(2)
		.exec(http("Browse_9")
			.get("/computers"))
		.pause(10)
}